""" Constants file for CFFA - this maps between .env/environment variables and constants used in CFFA.
"""
AUTH0_CLIENT_ID = 'AUTH0_CLIENT_ID'
AUTH0_CLIENT_SECRET = 'AUTH0_CLIENT_SECRET'
AUTH0_CALLBACK_URL = 'AUTH0_CALLBACK_URL'
AUTH0_DOMAIN = 'AUTH0_DOMAIN'
AUTH0_AUDIENCE = 'AUTH0_AUDIENCE'
PROFILE_KEY = 'profile'
""" Constants file for Auth0's seed project SECRET_KEY = 'ThisIsTheSecretKey'
"""

SECRET_KEY = 'SECRET_KEY'
JWT_PAYLOAD = 'jwt_payload'
PYTHONPATH = 'PYTHONPATH'
EXPORTDIRECTORY = 'EXPORTDIRECTORY'

""" Constants used to connect to MongoDB backend
"""

BACKEND_DBPWD = 'BACKEND_DBPWD'
BACKEND_DBUSR = 'BACKEND_DBUSR'
BACKEND_DBHOST = 'BACKEND_DBHOST'
BACKEND_DBPORT = 'BACKEND_DBPORT'
BACKEND_DBNAME = 'BACKEND_DBNAME'

""" Other constants
"""

GOOGLEKEYFILE='GOOGLEKEYFILE'
GOOGLE_SHEET='GOOGLE_SHEET'
TRANSACTION_SRC_WKSHEET='TRANSACTION_SRC_WKSHEET'
GAME_SRC_WKSHEET='GAME_SRC_WKSHEET'
CFFA_USERID='CFFA_USERID'
SUMMARY_SRC_WKSHEET='SUMMARY_SRC_WKSHEET'