# docker-compose.yaml for cffa
# It may be better to pass in the user changed settings via environmental variables like for MONGO_ROOT_USERNAME
# Also might be better to move the mongoDB directory to within cffa structure.
version: "3"
services:
    database:
        image: 'mongo'
        container_name: 'footballMongoDB'
        hostname: footballDB
        environment:
            - MONGO_INITDB_DATABASE=<The MongoDB football DB name - check your init-mongo.js db setting >
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
        volumes:
                - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
                - /opt/mongoCFFA:/data/db
        ports:
                - '27017-27019:27017-27019'
    reverseproxy:
        container_name: reverse
        hostname: reverse
        image: nginx:latest
        ports:
            - 80:80
            - 443:443
        volumes:
            - /home/ubuntu/cffa/letsencrypt/verification/:/etc/nginx/letsencrypt/verification/
            - /home/ubuntu/cffa/nginx/reverse_proxy.conf:/etc/nginx/conf.d/default.conf
            - /home/ubuntu/cffa/certs/nginx-selfsigned.crt:/etc/nginx/cert/nginx-selfsigned.crt
            - /home/ubuntu/cffa/certs/nginx-selfsigned.key:/etc/nginx/cert/nginx-selfsigned.key
            - /home/ubuntu/cffa/certs/nginx-proxy.pem:/etc/nginx/cert/nginx-proxy.pem
            - /home/ubuntu/cffa/certs/nginx-proxy.key:/etc/nginx/cert/nginx-proxy.key
            - /home/ubuntu/cffa/log/nginx:/var/log/cffa/
            - /home/ubuntu/cffa/cffa/static:/opt/cffa/static

    cffa_flask:
        container_name: cffa_flask
        hostname: cffa_flask
        image: cffa:latest
        #entrypoint: ["sh", "-c", "sleep 2073600"]
        ports:
            - 8000:5000
        environment:
            - SECRET_KEY=<a string to encrypt data by flask>
            - AUTH0_CLIENT_ID=<your Client ID for CFFA app>
            - AUTH0_DOMAIN=<your Auth0 Domain>
            - AUTH0_CLIENT_SECRET=<Your Client Secret for CFFA app>
            - AUTH0_CALLBACK_URL=<Your Client callback URL as configured in the Auth0 app configuration screen>
            - AUTH0_AUDIENCE=<Your Audience URL at Auth0>
            - BACKEND_DBPWD=<The MongoDB football DB password - check your init-mongo.js>
            - BACKEND_DBUSR=<The MongoDB football username - check your init-mongo.js>
            - BACKEND_DBHOST=database
            - BACKEND_DBPORT=27017
            - BACKEND_DBNAME=<The MongoDB football DB name - check your init-mongo.js >
            - EXPORTDIRECTORY=/home/cffa/cffa/ExportImport
        volumes:
            - /home/ubuntu/cffa/cffa/static:/home/cffa/static
            - /home/ubuntu/cffa/cffa/templates:/home/cffa/templates
            - /home/ubuntu/cffa/log/cffa:/home/cffa/logs
            - /home/ubuntu/cffa/certs/cffa-selfsigned.crt:/home/cffa/certs/cffa-selfsigned.crt
            - /home/ubuntu/cffa/certs/cffa-selfsigned.key:/home/cffa/certs/cffa-selfsigned.key
