apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-shared
spec:
  storageClassName: "example-storageclass"
  capacity:
    storage: 10G
  accessModes:
    - ReadOnlyMany
  claimRef:
    namespace: default
    name: pd-ssd-website-storage
  gcePersistentDisk:
    pdName: pd-ssd-cffawebsite
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pd-ssd-website-storage
spec:
  storageClassName: "example-storageclass"
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 10G
